// File generated by FlutterFire CLI or custom setup.
// Provides FirebaseOptions for Android, iOS, Web, macOS, Windows.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyWebForStiDistributionApp123',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'sti-distribution-commande',
    authDomain: 'sti-distribution-commande.firebaseapp.com',
    storageBucket: 'sti-distribution-commande.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJiluGoF02bPPsNbxSju_dFhzbmH9tKpE',
    appId: '1:682009942457:android:a9f1c198c5ff9d3694fe68',
    messagingSenderId: '682009942457',
    projectId: 'dz-sti-commande',
    storageBucket: 'dz-sti-commande.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyIosForStiDistributionApp123',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'sti-distribution-commande',
    storageBucket: 'sti-distribution-commande.appspot.com',
    iosBundleId: 'dz.sti.commande',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyMacosForStiDistribution123',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'sti-distribution-commande',
    storageBucket: 'sti-distribution-commande.appspot.com',
    iosBundleId: 'dz.sti.commande',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyWinForStiDistribution123',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'sti-distribution-commande',
    authDomain: 'sti-distribution-commande.firebaseapp.com',
    storageBucket: 'sti-distribution-commande.appspot.com',
  );
}
